# Lancement de ic-webapp
- name : "Launch ic-webapp container"
  docker_container:
    name: "{{ ic_webapp_name }}"
    image: "{{ ic_webapp_image }}"
    ports:
      - "{{ ic_webapp_port }}:8080"
    env:
      ODOO_URL: "{{ odoo_url }}"
      PGADMIN_URL: "{{ pgadmin_url }}"
