apiVersion: v1
kind: Service
metadata:
  name: bdd-odoo # Nom du Service qui permettra d'exposer le port de la BDD
  namespace: icgroup
  labels:
    env: prod
    name: bdd-odoo
spec:
  selector: # Sélection du Pod avec pour labels group=bdd et env=prod
    group: bdd # Label spécifique pour attacher ce qui est lié à la base de données au même service, et permettre la connexion à la base de données
    env: prod
  type: ClusterIP
  ports:
  - name: bdd-port
    port: 5432
    targetPort: bdd-access
