apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
  labels:
    env: prod
    type: local
  namespace: icgroup
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/pv1"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv2
  labels:
    env: prod
    type: local
  namespace: icgroup
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/pv2"

