---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin-pvclaim
  namespace: icgroup
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

