apiVersion: v1
kind: Pod
metadata:
  labels:
    app: pgadmin
    env: prod
    group: bdd
  name: pgadmin # Nom du Pod
  namespace: icgroup
spec:
  securityContext:
    runAsUser: 0 # Otherwise, the mounted volume is not writable
  containers:
    - name: pgadmin # Nom du container créé
      image: dpage/pgadmin4
      env:
        - name: PGADMIN_DEFAULT_EMAIL
          valueFrom:
            secretKeyRef:
              name: pgadmin
              key: PGADMIN_EMAIL
        - name: PGADMIN_DEFAULT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pgadmin
              key: PGADMIN_PASSWORD
      ports:
        - name: pgadmin-access # Nom donné au port à exposer via le Service pgadmin
          containerPort: 80
      volumeMounts:
        - name: pgadmin-data
          mountPath: /var/lib/pgadmin
        - name: pgadmin-config-volume
          mountPath: /pgadmin4
  volumes:
    - name: pgadmin-data
      persistentVolumeClaim:
        claimName: pgadmin-pvclaim
    - name: pgadmin-config-volume
      configMap:
        pgadmin-config
