apiVersion: v1
kind: Service
metadata:
  name: pgadmin # Nom du Service qui permettra d'exposer le port de la BDD
  namespace: icgroup
  labels:
    env: prod
    app: pgadmin
spec:
  type: NodePort
  selector:
    app: pgadmin
  ports:
    - name: pgadmin-port
      port: 8080 # Port for internal access through this  service; basically useless here
      targetPort: pgadmin-access # Internal port exposed by the app inside the Docker container
      nodePort: 30009 # Port for external access
