apiVersion: v1
kind: Pod
metadata:
  labels:
    app: pgadmin
    env: prod
    group: bdd
  name: pgadmin # Nom du Pod
  namespace: icgroup
spec:
  securityContext:
    runAsUser: 0 # Otherwise, the pgadmin-data volume is not writable
  containers:
    - name: pgadmin # Container name and address
      image: dpage/pgadmin4
      env:
        - name: PGADMIN_DEFAULT_EMAIL
          valueFrom:
            secretKeyRef:
              name: pgadmin
              key: PGADMIN_EMAIL
        - name: PGADMIN_DEFAULT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pgadmin
              key: PGADMIN_PASSWORD
      ports:
        - name: pgadmin-access # Name of the port exposed via the pgadmin Service
          containerPort: 80
      volumeMounts:
        - name: pgadmin-data
          mountPath: /var/lib/pgadmin
        - name: pgadmin-config-volume
          mountPath: /pgadmin4/servers.json
          subPath: servers.json
  volumes:
    - name: pgadmin-data
      persistentVolumeClaim:
        claimName: pgadmin-pvclaim
    - name: pgadmin-config-volume
      configMap:
        name: pgadmin-config
