apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-config
  namespace: icgroup
data:
  servers.json: |
    {
      "Servers": {
        "1": {
          "Name": "odoo-database",
          "Group": "Odoo",
          "Port": 5432,
          "Username": "odoo",
          "Host": "bdd-odoo",
          "SSLMode": "prefer",
          "MaintenanceDB": "postgres"
        }
      }
    }

