apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    env: prod
    app: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: maninax/ic-webapp:1.0
          env:
            - name: ODOO_URL
              value: https://www.odoo.com
            - name: PGADMIN_URL
              value: https://www.pgadmin.org
          ports:
            - name: webapp-access
              containerPort: 8080
