---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv3
  labels:
    env: prod
    type: local
  namespace: icgroup
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/pv3"
