---
- name: "Generate docker-compose-odoo.yml file from template"
  template:
    src: "docker-compose-odoo.yml.j2"
    dest: /home/{{ ansible_user }}/docker-compose-odoo.yml
    mode: 0655

- name: "Deploy using docker-compose-odoo.yml"
  command: "docker compose -f /home/{{ ansible_user }}/docker-compose-odoo.yml up -d"

- name: "Preconfigure Odoo"
  command: "curl http://localhost:{{ odoo_port }}/web/database/create --data 'master_pwd={{ postgres_password }}&name={{ odoo_database }}&login={{ odoo_username }}&password={{ odoo_password }}&demo=1' --compressed"
  no_log: True
