---
- name: "Generate docker-compose file"
  template:
    src: "docker-compose-pgadmin.yml.j2"
    dest: /home/{{ ansible_user }}/docker-compose-pgadmin.yml
    mode: 0655

- name: "Generate pgadmin initial config file"
  template:
    src: "servers.json.j2"
    dest: /home/{{ ansible_user }}/servers.json
    mode: 0655

- name: "Deploy using docker-compose-pgadmin.yml"
  command: "docker compose -f /home/{{ ansible_user }}/docker-compose-pgadmin.yml up -d"
