apiVersion: v1
kind: Pod
metadata:
  labels:
    app: bdd-odoo
    env: prod
    group: bdd
  name: bdd-odoo # Nom du Pod
  namespace: icgroup
spec:
  containers:
    - name: bdd-odoo # Nom du container créé
      image: postgres
      env:
        - name: POSTGRES_DB
          value: postgres # Si non défini, défaut: $POSTGRES_USER et l'initialisation d'Odoo échouera
        - name: PGDATA
          value: /var/lib/postgresql/data
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: bdd-odoo
              key: BDD_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bdd-odoo
              key: BDD_PASSWORD
      ports:
        - name: bdd-access # Nom donné au port à exposer via le Service bdd-odoo (ClusterIP)
          containerPort: 5432
      volumeMounts:
        - name: bdd-odoo-data # Nom du volume à employer
          mountPath: /var/lib/postgresql/data # Nom du dossier où pgsql sauvegarde sa base de données
  volumes:
    - name: bdd-odoo-data
      persistentVolumeClaim:
        claimName: bdd-odoo-pvclaim
