apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-pvclaim
  namespace: icgroup
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bdd-odoo-pvclaim
  namespace: icgroup
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

