---
# defaults file for pgadmin_role
pgadmin_data_volume: pgadmin_data
pgadmin_network: ic_network_pgadmin
pg_admin_email: test@test.com
pg_admin_password: testingtest
pgadmin_service_name: pgadmin
pgadmin_container_name: pgadmin
pg_admin_init_config_name: odoo-database
pg_admin_init_config_group: Odoo
pg_admin_init_config_host: postgres
pg_admin_init_config_username: odoo
